env:
    browser: true
    es2021: true
    node: true
    jest: true
extends:
    - 'plugin:react/recommended'
    - airbnb
parser: '@typescript-eslint/parser'
parserOptions:
    ecmaFeatures:
        jsx: true
    ecmaVersion: 12
    sourceType: module
plugins:
    - react
    - '@typescript-eslint'
rules: {
    "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx", ".tsx"] }],
    "react/react-in-jsx-scope": "off",
    "import/extensions": ["error", { "js": "never" }],
    "quotes": ["error", "double"],
    "indent": ["error", 4, { "ignoredNodes": ["JSXElement *"] }],
    "react/jsx-indent": [2, 4],
    "react/jsx-indent-props": [2, 4],
    "import/prefer-default-export": "off"
}
settings: {
    "import/resolver": {
        "node": {
            "extensions": [".js", ".jsx", ".ts", ".tsx"]
        }
    }
}